### ISSUE TITLE
About Implimenting Partitions in ConsenSys's ERC1400

### ISSUE THREAD

**Issue by hamadayukinori** [ConsenSys/ERC1400#30]
I read all smart contracts file in this ERC1400 example And  the slides(Slide deck presenting ERC1400 features:) provided in ConsenSys.

The slide explains that partitions represent Asset state and Asset class in hex. But in ERC1400 Example  partitions has only 3 state.  And I have not understood how to write partitions representing  different assets state and class in hex in details. 

Has anyone concrete example codes?

**Comment by gauthierpetetin** [comment]
Partitions, are 32 bytes long, and can be used to represent whatever you want.
The 3 states (Locked, Reserved, Issued) in the slide deck are an example. But you can define the states you want.
Example:
"Locked" converted in hexadecimal is 4c6f636b6564.
So the name of the partition (32 bytes long) becomes:
0x4c6f636b65640000000000000000000000000000000000000000000000000000
https://codebeautify.org/string-hex-converter
