### ISSUE TITLE
yarn install fails when using node version > 10

### ISSUE THREAD

**Issue by manosamy** [ConsenSys/ERC1400#42]
I tried node 12.x, 13.x on windows and mac, build fails for all those combinations at
node-gyp rebuild

node version 10.x works fine (it worked for me with 10.18.0 on windows)

Please add this to the readme, could save time for someone.

**Comment by gauthierpetetin** [comment]
Thanks, we'll mention it in the README.

**Comment by Djiit** [comment]
Closing this as the recommended version is now node 12.
