### ISSUE TITLE
Multiple token issuance

### ISSUE THREAD

**Issue by victorwiebe** [ConsenSys/ERC1400#49]
Hi there! Hope you guys are doing well.

I am writing to you about multiple token issuance. I have been playing with that. I wrote a little module which calls issueByPartition multiple times. Obviously this is necessary because I am not going to call 100 times issueByPartition, I want to call 1 transaction call to issue for 100 investors.

```
    function issueByPartitionMultiple(bytes32[] calldata partitions,
        address[] calldata tokenHolders,
        uint256[] calldata values,
        bytes calldata data)
    external
    withControllerPermission //checks controller permission on contract, modifier works on other calls.
    {
        require(partitions.length == tokenHolders.length, "Check array lengths");
        require(partitions.length == values.length, "Check array lengths");
        for (uint i=0; i < partitions.length; i++) {
            IERC1400(address(securityToken))
            .issueByPartition(partitions[i], tokenHolders[i], values[i], data);
        }
    }
```

How have you guys solved this issue?

**Comment by gauthierpetetin** [comment]
Hi @victorwiebe , thanks for your comment.
Indeed, transaction batching is an important topic.
We've added a "BatchTokenIssuer" to the repo, you can find [here](https://github.com/ConsenSys/ERC1400/blob/master/contracts/tools/BatchTokenIssuer.sol) now.

The maximum number of token issuances that can be done in one single transaction is 46 with this implementation.

**Comment by victorwiebe** [comment]
That is interesting as well thank you @gauthierpetetin 

Can you please clarify why 46 is the maximum number? Is this due to gas restrictions? How do you estimate that

**Comment by gauthierpetetin** [comment]
Yes it's due to gas restrictions.

You can play with it by updating the number in the [unit tests](https://github.com/ConsenSys/ERC1400/blob/master/test/BatchTokenIssuer.test.js) (l.22):
`const MAX_NUMBER_OF_ISSUANCES_IN_A_BATCH = 46;`
