### ISSUE TITLE
How data conservation is handled during the migrations ?

### ISSUE THREAD

**Issue by ArvsIndrarys** [ConsenSys/ERC1400#56]
The [ERC1400](https://github.com/ConsenSys/ERC1400/blob/master/contracts/ERC1400.sol) seems to hold all the data of the implementation.
Its [migration code](https://github.com/ConsenSys/ERC1400/blob/master/contracts/ERC1400.sol#L1274) seems to only update the reference in the ERC1820 contract.

I wonder how data migration is handled? Is it not? Or is there a mecanism to access the data of the base contract from the new one ? And why not have a storage contract to handle this?

**Comment by gauthierpetetin** [comment]
Hello @ArvsIndrarys,
Thanks for you question. Indeed the migration code only updates the reference in the ERC1820 contract. There's no mechanism to access the data of the base contract from the new one (tokens need to be re-minted in that case), which encourages to place the "upgradeable code" in a token extension contract, while the core ERC1400 code shall remain the same.
Having a storage contract would be interesting as well but is not done in this implementation.

**Comment by ArvsIndrarys** [comment]
Hello @gauthierpetetin !
Thanks for answering, you can close the issue :)
